#=== Financial System Configuration ===#
EnableFinancialSystem: true  # 금융 시스템 활성화 여부
InitialMoney: 10000  # 첫 소지금
DefaultShopRatio: 5  # 기본 상점 비율(미사용)
StockMinimumRatio: 0.7  # 주식의 변동 최소 배율
StockMaximumRatio: 1.3  # 주식의 변동 최대 배율
StockStandardDeviation: 0.1  # 주식 변동 표준 편차(추천: (최대배율 - 최소배율) / 5)
StockPriceDrag: 0.1  # 주식의 가격 회귀율, 반드시 1 이하로 할 것, 0으로 두면 중앙복귀 조정이 없으며 가격이 0으로 수렴 또는 무한대로 발산할 수 있음
StockInterval: 10  # 주식의 변동 주기 (분), 60의 약수 중 2 이상으로 설정할 것
#=== Financial System Configuration End ===#

#=== Ability System Configuration ===#
EnableAbilitySystem: true  # 능력 시스템 활성화 여부
InitialTicket: 10  # 첫 뽑기권 수
InitialCOMMON: 1  # 첫 COMMON 선택권 수
InitialRARE: 1  # 첫 RARE 선택권 수
InitialEPIC: 1  # 첫 EPIC 선택권 수

LEGENDARYProbability:  # LEGENDARY 등급 등장 확률
  Base: 0.005  # 기본 뽑기 확률
  Increment: 0.05  # 뽑기 확률 증가량
  IncreaseCount: 81  # 위의 증가량이 적용되기 시작하는 횟수

EPICProbability:  # EPIC 등급 등장 확률
  Base: 0.03  # 기본 뽑기 확률
  Increment: 0.3  # 뽑기 확률 증가량
  IncreaseCount: 7  # 위의 증가량이 적용되기 시작하는 횟수

TROLLProbability: 0.01  # TROLL 등급 등장 확률
ForceTroll: true  # TROLL 능력이 뽑기에서 등장 시 강제 적용 여부

